pipeline {
    agent any
    environment {
        MINIKUBE_HOME = '/var/lib/jenkins'
    }
    stages {
        stage('Initialize') {
            steps {
                echo 'Starting pipeline'
            }
        }

        stage('Run Stages in Subdirectory') {
            steps {
                script {
                    // Define the helper function
                    def runInMyDir = { stageName, body ->
                        stage(stageName) {
                            dir('samplenodeproject') {
                                body()
                            }
                        }
                    }

                    runInMyDir('Set Docker Env for Minikube') {
                        sh '''
                            export MINIKUBE_HOME=/var/lib/jenkins
                            eval $(minikube docker-env)
                            docker info
                        '''
                    }

                    runInMyDir('Build Docker Image') {
                        sh '''
                            export MINIKUBE_HOME=/var/lib/jenkins
                            eval $(minikube docker-env)
                            docker build -t nodeapp .
                        '''
                    }

                    runInMyDir('Test') {
                        sh '''
                            export MINIKUBE_HOME=/var/lib/jenkins
                            eval $(minikube docker-env)
                            echo "testing..."
                            docker inspect --type=image nodeapp:latest
                        '''
                    }

                    runInMyDir('Deploy') {
                        sh '''
                            export MINIKUBE_HOME=/var/lib/jenkins
                            eval $(minikube docker-env)
                            kubectl apply -f deployment.yaml
                        '''
                    }

                    // Optional: To run without Kubernetes, use Docker run
                    // runInMyDir('Deploy (Local Docker Run)') {
                    //     sh '''
                    //         export MINIKUBE_HOME=/var/lib/jenkins
                    //         eval $(minikube docker-env)
                    //         docker run -d --name nodeappcontainer -p 5000:5000 nodeapp:latest
                    //     '''
                    // }
                }
            }
        }
    }
}
